### ISSUE TITLE
Improved release workflow

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#656]
**Description**

The security config should always point to the latest image from main.

Proposal:
- add a "main" tag to the image so that the security-config on main don't need to get touched, as well as IMG in makefile
- do the image bump on release branches only to assure that we don't need to tamper the "main" image
- requires to fix the changelog generation problem on release branches

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by chrkl** [comment]
PR https://github.com/kyma-project/test-infra/pull/9602 adds a main tag to any post-submit image build. #684 uses the main tag in the repository and updates the release flow documentation. Generating proper change logs has been successfully tested without changes to the goreleaser config. The behaviour is as follows:
- The changelog for regular releases contains all commits since the last release. For instance, 1.6.0 contains all changes after 1.5.0. Even if a bugfix release (1.5.1) exists in between.
- Bugfix releases generate release notes with all changes since the last regular release. For instance, 1.5.1 contains alls PRs after 1.5.0.
- If a bugfix release contains cherry-picked changes, these will appear again in the change log of the next regular release. Goreleaser can handle cherry-picks in general. However, since we would create a new PR for a cherry-pick, goreleaser does not detect them properly.
